image: docker:20.10.24

pipelines:
  branches:
    master:
      - step:
          services:
            - docker
          script:
            - git clone https://bitbucket.org/siroe/siroe-deploy-scripts.git
            - chmod +x siroe-deploy-scripts/siroe-apps.sh
            - sh siroe-deploy-scripts/siroe-apps.sh

    develop:
      - step:
          services:
            - docker
          script:
            - git clone https://bitbucket.org/siroe/siroe-deploy-scripts.git
            - chmod +x siroe-deploy-scripts/siroe-apps.sh
            - sh siroe-deploy-scripts/siroe-apps.sh

    "feature/**":
      - step:
          services:
            - docker
          script:
            - git clone https://bitbucket.org/siroe/siroe-deploy-scripts.git
            - chmod +x siroe-deploy-scripts/siroe-apps.sh
            - sh siroe-deploy-scripts/siroe-apps.sh