image: docker:20.10.24

pipelines:
  branches:
    master:
      - step:
          services:
            - docker
          script:
            - docker build -t siroe/$APP_NAME:latest .
            - docker save siroe/$APP_NAME:latest | gzip > image.tar.gz

            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: 'root'
                SERVER: $SERVER
                SSH_KEY: $SSH_KEY
                REMOTE_PATH: "/root/apps/$APP_NAME"
                LOCAL_PATH: "image.tar.gz"
                EXTRA_ARGS: "-o StrictHostKeyChecking=no"

            - pipe: atlassian/ssh-run:0.4.1
              variables:
                SSH_USER: 'root'
                SERVER: $SERVER
                SSH_KEY: $SSH_KEY
                EXTRA_ARGS: "-o StrictHostKeyChecking=no"
                COMMAND: |
                  set -e
                  mkdir -p /root/apps/$APP_NAME
                  cd /root/apps/$APP_NAME

                  echo "$ENV_FILE" > .env
                  docker load < image.tar.gz

                  cat > docker-compose.yml <<EOF
                  version: "3.8"

                  services:
                    api:
                      image: siroe/$APP_NAME:latest
                      container_name: $APP_NAME
                      restart: always
                      env_file:
                        - .env
                      labels:
                        - "traefik.enable=true"
                        - "traefik.http.routers.$APP_NAME.rule=Host($APP_HOST)"
                        - "traefik.http.routers.$APP_NAME.entrypoints=web"
                  EOF

                  docker-compose up -d

definitions:
  services:
    docker:
      memory: 2048