image: docker:20.10.24

pipelines:
  branches:
    master:
      - step:
          services:
            - docker
          script:
            - apk add --no-cache git
            - git clone https://x-token-auth:$BB_TOKEN@bitbucket.org/siroe/siroe-devops-scripts.git
            - chmod +x siroe-devops-scripts/siroe-apps.sh
            - sh siroe-devops-scripts/siroe-apps.sh

    develop:
      - step:
          services:
            - docker
          script:
            - apk add --no-cache git
            - git clone https://x-token-auth:$BB_TOKEN@bitbucket.org/siroe/siroe-devops-scripts.git
            - chmod +x siroe-devops-scripts/siroe-apps.sh
            - sh siroe-devops-scripts/siroe-apps.sh

    "feature/**":
      - step:
          services:
            - docker
          script:
            - apk add --no-cache git
            - git clone https://x-token-auth:$BB_TOKEN@bitbucket.org/siroe/siroe-devops-scripts.git
            - chmod +x siroe-devops-scripts/siroe-apps.sh
            - sh siroe-devops-scripts/siroe-apps.sh